export const BuildingEquipment = [
  {
    id: "21",
    itemname: "Red Clay Bricks",
    category: "Bricks",
    description: "High-quality red clay bricks for construction",
    imgUrl: "../Assets/building/b1.jpeg",
    price: "200",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "22",
    itemname: "Concrete Bricks",
    category: "Bricks",
    description: "Concrete bricks for various construction purposes",
    imgUrl: "../Assets/building/b2.jpeg",
    price: "180",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "23",
    itemname: "Fire Bricks",
    category: "Bricks",
    description: "Fire-resistant bricks suitable for kilns and fireplaces",
    imgUrl: "../Assets/building/b3.jpeg",
    price: "250",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "24",
    itemname: "Hollow Bricks",
    category: "Bricks",
    description: "Lightweight hollow bricks for efficient construction",
    imgUrl: "../Assets/building/b4.png",
    price: "220",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "25",
    itemname: "Fly Ash Bricks",
    category: "Bricks",
    description:
      "Eco-friendly bricks made from fly ash for sustainable construction",
    imgUrl: "../Assets/building/b5.jpeg",
    price: "230",
    oldprice: "249",
    offer: "10",
  },

  {
    id: "26",
    itemname: "Portland Cement",
    category: "Cement",
    description: "High-quality Portland cement for superior concrete strength",
    imgUrl: "../Assets/building/b6.jpeg",
    price: "50",
    oldprice: "249",

    offer: "10",
  },
  {
    id: "27",
    itemname: "White Cement",
    category: "Cement",
    description: "Specialized white cement for architectural applications",
    imgUrl: "../Assets/building/b7.jpeg",
    price: "70",
    oldprice: "249",

    offer: "10",
  },
  {
    id: "28",
    itemname: "Rapid Hardening Cement",
    category: "Cement",
    description: "Cement with accelerated setting time for quick construction",
    imgUrl: "../Assets/building/b8.jpeg",
    price: "60",
    oldprice: "249",

    offer: "10",
  },
  {
    id: "29",
    itemname: "Blended Cement",
    category: "Cement",
    description:
      "Blended cement with added pozzolanic materials for enhanced durability",
    imgUrl: "../Assets/building/b9.jpeg",
    price: "55",
    oldprice: "249",

    offer: "10",
  },
  {
    id: "30",
    itemname: "Masonry Cement",
    category: "Cement",
    description: "Specialized cement for masonry applications",
    imgUrl: "../Assets/building/b10.jpeg",
    price: "65",
    oldprice: "249",

    offer: "10",
  },

  {
    id: "31",
    itemname: "12mm Iron Rods",
    category: "Iron",
    description:
      "High-quality 12mm iron rods for reinforcement in construction",
    imgUrl: "../Assets/building/b11.jpeg",
    price: "300",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "32",
    itemname: "10mm Iron Rods",
    category: "Iron",
    description: "Durable 10mm iron rods for structural support",
    imgUrl: "../Assets/building/b12.jpeg",
    price: "280",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "33",
    itemname: "TMT Bars",
    category: "Iron",
    description: "Thermo Mechanically Treated (TMT) bars for superior strength",
    imgUrl: "../Assets/building/b13.jpeg",
    price: "320",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "34",
    itemname: "Ribbed Bars",
    category: "Iron",
    description: "Ribbed iron bars for increased bond strength in concrete",
    imgUrl: "../Assets/building/b14.jpeg",
    price: "310",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "35",
    itemname: "Corrugated Iron Sheets",
    category: "Iron",
    description: "Corrugated iron sheets for roofing and siding applications",
    imgUrl: "../Assets/building/b15.jpeg",
    price: "350",
    oldprice: "249",
    offer: "10",
  },

  {
    id: "36",
    itemname: "Marine Plywood",
    category: "Woods",
    description: "Marine-grade plywood for formwork and exterior applications",
    imgUrl: "../Assets/building/b16.jpeg",
    price: "150",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "37",
    itemname: "Hardwood Plywood",
    category: "Woods",
    description: "Durable hardwood plywood for various construction projects",
    imgUrl: "../Assets/building/b17.jpeg",
    price: "170",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "38",
    itemname: "Softwood Plywood",
    category: "Woods",
    description: "Lightweight softwood plywood for interior applications",
    imgUrl: "../Assets/building/b18.jpeg",
    price: "140",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "39",
    itemname: "MDF Boards",
    category: "Woods",
    description:
      "Medium Density Fiberboard (MDF) boards for furniture and cabinetry",
    imgUrl: "../Assets/building/b19.jpeg",
    price: "160",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "40",
    itemname: "Particle Boards",
    category: "Woods",
    description: "Particle boards for cost-effective construction solutions",
    imgUrl: "../Assets/building/b20.jpeg",
    price: "130",
    oldprice: "249",
    offer: "10",
  },

  {
    id: "41",
    itemname: "Crushed Stone Aggregate",
    category: "Crushed stone",
    description:
      "Crushed stone aggregate for base material in road construction",
    imgUrl: "../Assets/building/b21.jpeg",
    price: "80",
    oldprice: "249",

    offer: "10",
  },
  {
    id: "42",
    itemname: "Recycled Concrete Aggregate",
    category: "Crushed stone",
    description:
      "Eco-friendly recycled concrete aggregate for sustainable construction",
    imgUrl: "../Assets/building/b22.jpeg",
    price: "90",
    oldprice: "249",

    offer: "10",
  },
  {
    id: "43",
    itemname: "Granite Chips",
    category: "Crushed stone",
    description: "Granite chips for decorative landscaping and pathways",
    imgUrl: "../Assets/building/b23.jpeg",
    price: "85",
    oldprice: "249",

    offer: "10",
  },
  {
    id: "44",
    itemname: "Limestone Aggregate",
    category: "Crushed stone",
    description: "Limestone aggregate for drainage and erosion control",
    imgUrl: "../Assets/building/b24.jpeg",
    price: "75",
    oldprice: "249",

    offer: "10",
  },
  {
    id: "45",
    itemname: "Quartzite Aggregate",
    category: "Crushed stone",
    description: "Quartzite aggregate for high-strength concrete mixes",
    imgUrl: "../Assets/building/b25.jpeg",
    price: "95",
    oldprice: "249",

    offer: "10",
  },

  {
    id: "46",
    itemname: "River Sand",
    category: "Sand",
    description: "Natural river sand for concrete mixing and plastering",
    imgUrl: "../Assets/building/b26.jpeg",
    price: "120",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "47",
    itemname: "Pit Sand",
    category: "Sand",
    description: "Pit sand for various construction applications",
    imgUrl: "../Assets/building/b27.jpeg",
    price: "110",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "48",
    itemname: "Plastering Sand",
    category: "Sand",
    description: "Fine plastering sand for smooth finishes on walls",
    imgUrl: "../Assets/building/b28.jpeg",
    price: "130",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "49",
    itemname: "Filter Sand",
    category: "Sand",
    description: "Filter sand for water filtration systems and septic tanks",
    imgUrl: "../Assets/building/b29.jpeg",
    price: "125",
    oldprice: "249",
    offer: "10",
  },
  {
    id: "50",
    itemname: "Silica Sand",
    category: "Sand",
    description: "Silica sand for glass making and industrial applications",
    imgUrl: "../Assets/building/b30.jpeg",
    price: "140",
    oldprice: "249",
    offer: "10",
  },
];
