export const construction_equipment = [
  {
    id: "51",
    itemname: "Wire Cutter",
    category: "Wire Cutters",
    description: "Heavy-duty wire cutter for construction use",
    imgUrl: "../Assets/electrical/E1.jpeg",
    price: "50",

    oldprice: "249",
    offer: "25",
  },
  {
    id: "52",
    itemname: "Steel Wire",
    category: "Wires",
    description: "High-tensile strength steel wire for construction purposes",
    imgUrl: "../Assets/electrical/e2.jpeg",
    price: "20",

    oldprice: "249",
    offer: "25",
  },
  {
    id: "53",
    itemname: "Circuit Breaker",
    category: "Circuits",
    description: "Electrical circuit breaker for building wiring",
    imgUrl: "../Assets/electrical/e3.jpeg",
    price: "150",
    oldprice: "249",
    offer: "25",
  },
  {
    id: "54",
    itemname: "Electrical Panel",
    category: "Panels",
    description: "Control panel for electrical distribution in buildings",
    imgUrl: "../Assets/electrical/e4.jpeg",
    price: "300",
    oldprice: "249",
    offer: "25",
  },
  {
    id: "55",
    itemname: "Wire Stripper",
    category: "Wire Cutters",
    description: "Tool for stripping insulation from wires",
    imgUrl: "../Assets/electrical/e6.jpeg",
    price: "40",
    oldprice: "249",
    offer: "25",
  },
  {
    id: "56",
    itemname: "Copper Wire",
    category: "Wires",
    description: "High-conductivity copper wire for electrical connections",
    imgUrl: "../Assets/electrical/e7.jpeg",
    price: "30",

    oldprice: "249",
    offer: "25",
  },
  {
    id: "57",
    itemname: "Fuse Box",
    category: "Circuits",
    description: "Fuse box for electrical safety in buildings",
    imgUrl: "../Assets/electrical/e8.jpeg",
    price: "100",
    oldprice: "249",
    offer: "25",
  },
  {
    id: "58",
    itemname: "Distribution Board",
    category: "Panels",
    description: "Distribution board for controlling electrical circuits",
    imgUrl: "../Assets/electrical/e9.jpeg",
    price: "250",
    oldprice: "249",
    offer: "25",
  },

  {
    id: "59",
    itemname: "Wire Crimper",
    category: "Wire Cutters",
    description: "Tool for crimping wire connectors",
    imgUrl: "../Assets/electrical/e11.jpeg",
    price: "35",
    oldprice: "249",
    offer: "25",
  },
  {
    id: "60",
    itemname: "Aluminum Wire",
    category: "Wires",
    description: "Lightweight aluminum wire for construction applications",
    imgUrl: "../Assets/electrical/e12.jpeg",
    price: "25",
    oldprice: "249",
    offer: "25",
  },
  {
    id: "61",
    itemname: "Switch Box",
    category: "Circuits",
    description: "Switch box for controlling electrical devices",
    imgUrl: "../Assets/electrical/e13.jpeg",
    price: "80",
    oldprice: "249",
    offer: "25",
  },
  {
    id: "62",
    itemname: "Meter Box",
    category: "Panels",
    description: "Meter box for measuring electrical consumption",
    imgUrl: "../Assets/electrical/e14.jpeg",
    price: "200",
    oldprice: "249",
    offer: "25",
  },
  {
    id: "63",
    itemname: "Wire Bender",
    category: "Wire Cutters",
    description: "Tool for bending wires into desired shapes",
    imgUrl: "../Assets/electrical/e16.jpeg",
    price: "45",
    oldprice: "249",
    offer: "25",
  },
  {
    id: "64",
    itemname: "Fiber Optic Cable",
    category: "Wires",
    description: "High-speed fiber optic cable for data transmission",
    imgUrl: "../Assets/electrical/e17.png",
    price: "50",

    oldprice: "249",
    offer: "25",
  },
  {
    id: "65",
    itemname: "Surge Protector",
    category: "Circuits",
    description: "Surge protector for safeguarding electrical equipment",
    imgUrl: "../Assets/electrical/e18.jpeg",
    price: "120",
    oldprice: "249",
    offer: "25",
  },
  {
    id: "66",
    itemname: "Control Panel Box",
    category: "Panels",
    description: "Control panel box for industrial automation systems",
    imgUrl: "../Assets/electrical/e19.jpeg",
    price: "400",
    oldprice: "249",
    offer: "25",
  },
  {
    id: "67",
    itemname: "Wire Twister",
    category: "Wire Cutters",
    description: "Tool for twisting multiple wires together",
    imgUrl: "../Assets/electrical/e21.jpeg",
    price: "55",

    oldprice: "249",
    offer: "25",
  },
  {
    id: "68",
    itemname: "Cat 6 Ethernet Cable",
    category: "Wires",
    description: "High-speed Ethernet cable for networking applications",
    imgUrl: "../Assets/electrical/e22.jpeg",
    price: "15",

    oldprice: "249",
    offer: "25",
  },
  {
    id: "69",
    itemname: "Voltage Regulator",
    category: "Circuits",
    description: "Voltage regulator for stabilizing electrical voltage",
    imgUrl: "../Assets/electrical/e23.jpeg",
    price: "90",
    oldprice: "249",
    offer: "25",
  },
  {
    id: "70",
    itemname: "Power Distribution Panel",
    category: "Panels",
    description: "Power distribution panel for large-scale electrical systems",
    imgUrl: "../Assets/electrical/e24.jpeg",
    price: "600",
    oldprice: "249",
    offer: "25",
  },
  {
    id: "71",
    itemname: "PVC Pipes",
    category: "Pipes",
    description: "Durable PVC pipes for plumbing and drainage systems",
    imgUrl: "../Assets/electrical/e26.jpeg",
    price: "10",

    oldprice: "249",
    offer: "25",
  },
  {
    id: "72",
    itemname: "Pipe Cutter",
    category: "Pipes",
    description: "Tool for cutting PVC and metal pipes",
    imgUrl: "../Assets/electrical/e27.jpeg",
    price: "35",

    oldprice: "249",
    offer: "25",
  },
  {
    id: "73",
    itemname: "Water Pump",
    category: "Pipes",
    description: "Water pump for construction site dewatering",
    imgUrl: "../Assets/electrical/e28.jpeg",
    price: "150",
    oldprice: "249",
    offer: "25",
  },
  {
    id: "74",
    itemname: "Pipe Fittings",
    category: "Pipes",
    description: "Various fittings for connecting PVC pipes",
    imgUrl: "../Assets/electrical/e29.jpeg",
    price: "5",

    oldprice: "249",
    offer: "25",
  },
  {
    id: "75",
    itemname: "Pipe Wrench",
    category: "Pipes",
    description: "Adjustable wrench for gripping and turning pipes",
    imgUrl: "../Assets/electrical/e30.jpeg",
    price: "20",

    oldprice: "249",
    offer: "25",
  },
];
