export const Items = [
  {
    id: "1",
    itemname: "Cable",
    category: "Electrical",
    description: "1m cable in red color",
    image_url: "../Assets/random.jpg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "2",
    itemname: "Hammer",
    category: "Hard Tools",
    description: "10-inch hammer with wooden handle",
    image_url: "../Assets/EquipmentImages/2.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "3",
    itemname: "Excavator",
    category: "Heavy Machinery",
    description:
      "Caterpillar excavator with bucket capacity of 1.5 cubic meters",
    image_url: "../Assets/EquipmentImages/3.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "4",
    itemname: "Ladder",
    category: "Ladders",
    description: "8-foot aluminum ladder with non-slip steps",
    image_url: "../Assets/EquipmentImages/4.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "5",
    itemname: "Hard Hat",
    category: "Safety Gear",
    description: "Yellow hard hat with adjustable strap",
    image_url: "../Assets/EquipmentImages/5.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "6",
    itemname: "Extension Cord",
    category: "Electrical",
    description: "25-foot extension cord with three outlets",
    image_url: "../Assets/EquipmentImages/6.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "7",
    itemname: "Drill",
    category: "Hard Tools",
    description: "Cordless drill with variable speed settings",
    image_url: "../Assets/EquipmentImages/7.webp",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "8",
    itemname: "Bulldozer",
    category: "Heavy Machinery",
    description: "Komatsu bulldozer with blade width of 10 feet",
    image_url: "../Assets/EquipmentImages/8.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "9",
    itemname: "Safety Harness",
    category: "Safety Gear",
    description: "Full-body safety harness with shock-absorbing lanyard",
    image_url: "../Assets/EquipmentImages/9.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "10",
    itemname: "Scaffolding",
    category: "Ladders",
    description: "Steel scaffolding with adjustable height",
    image_url: "../Assets/EquipmentImages/10.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "11",
    itemname: "Welding Machine",
    category: "Heavy Machinery",
    description: "Miller welding machine with 200-amp output",
    image_url: "../Assets/EquipmentImages/11.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "12",
    itemname: "Safety Goggles",
    category: "Safety Gear",
    description: "Clear safety goggles with anti-fog coating",
    image_url: "../Assets/EquipmentImages/12.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "13",
    itemname: "Power Saw",
    category: "Hard Tools",
    description: "Circular power saw with carbide-tipped blade",
    image_url: "../Assets/EquipmentImages/13.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "14",
    itemname: "Generator",
    category: "Electrical",
    description: "Honda generator with 5000-watt output",
    image_url: "../Assets/EquipmentImages/14.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "15",
    itemname: "Concrete Mixer",
    category: "Heavy Machinery",
    description: "Portable concrete mixer with 3-cubic-foot drum",
    image_url: "../Assets/EquipmentImages/15.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "16",
    itemname: "Safety Vest",
    category: "Safety Gear",
    description: "High-visibility safety vest with reflective strips",
    image_url: " ../Assets/EquipmentImages/16.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "17",
    itemname: "Air Compressor",
    category: "Hard Tools",
    description: "Portable air compressor with 6-gallon tank",
    image_url: " ../Assets/EquipmentImages/17.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "18",
    itemname: "Forklift",
    category: "Heavy Machinery",
    description: "Toyota forklift with lifting capacity of 5000 pounds",
    image_url: " ../Assets/EquipmentImages/18.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "19",
    itemname: "Fall Protection Kit",
    category: "Safety Gear",
    description: "Fall protection kit with harness, lanyard, and anchor point",
    image_url: "../Assets/EquipmentImages/19.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
  {
    id: "20",
    itemname: "Chainsaw",
    category: "Hard Tools",
    description: "Gas-powered chainsaw with 18-inch bar",
    image_url: " ../Assets/EquipmentImages/20.jpeg",
    price: "10.00",
    oldprice: "249",
    offer: "15",
  },
];
