export const productData = [
  {
    id: "1",
    itemname: "Cable",
    category: "Electrical",
    description: "1m cable in red color",
    imgUrl: "../Assets/random.jpg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "2",
    itemname: "Hammer",
    category: "Hard Tools",
    description: "10-inch hammer with wooden handle",
    imgUrl: "../Assets/EquipmentImages/2.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "3",
    itemname: "Excavator",
    category: "Heavy Machinery",
    description:
      "Caterpillar excavator with bucket capacity of 1.5 cubic meters",
    imgUrl: "../Assets/EquipmentImages/3.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "4",
    itemname: "Ladder",
    category: "Ladders",
    description: "8-foot aluminum ladder with non-slip steps",
    imgUrl: "../Assets/EquipmentImages/4.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "5",
    itemname: "Hard Hat",
    category: "Safety Gear",
    description: "Yellow hard hat with adjustable strap",
    imgUrl: "../Assets/EquipmentImages/5.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "6",
    itemname: "Extension Cord",
    category: "Electrical",
    description: "25-foot extension cord with three outlets",
    imgUrl: "../Assets/EquipmentImages/6.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "7",
    itemname: "Drill",
    category: "Hard Tools",
    description: "Cordless drill with variable speed settings",
    imgUrl: "../Assets/EquipmentImages/7.webp",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "8",
    itemname: "Bulldozer",
    category: "Heavy Machinery",
    description: "Komatsu bulldozer with blade width of 10 feet",
    imgUrl: "../Assets/EquipmentImages/8.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "9",
    itemname: "Safety Harness",
    category: "Safety Gear",
    description: "Full-body safety harness with shock-absorbing lanyard",
    imgUrl: "../Assets/EquipmentImages/9.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "10",
    itemname: "Scaffolding",
    category: "Ladders",
    description: "Steel scaffolding with adjustable height",
    imgUrl: "../Assets/EquipmentImages/10.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "11",
    itemname: "Welding Machine",
    category: "Heavy Machinery",
    description: "Miller welding machine with 200-amp output",
    imgUrl: "../Assets/EquipmentImages/11.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "12",
    itemname: "Safety Goggles",
    category: "Safety Gear",
    description: "Clear safety goggles with anti-fog coating",
    imgUrl: "../Assets/EquipmentImages/12.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "13",
    itemname: "Power Saw",
    category: "Hard Tools",
    description: "Circular power saw with carbide-tipped blade",
    imgUrl: "../Assets/EquipmentImages/13.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "14",
    itemname: "Generator",
    category: "Electrical",
    description: "Honda generator with 5000-watt output",
    imgUrl: "../Assets/EquipmentImages/14.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "15",
    itemname: "Concrete Mixer",
    category: "Heavy Machinery",
    description: "Portable concrete mixer with 3-cubic-foot drum",
    imgUrl: "../Assets/EquipmentImages/15.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "16",
    itemname: "Safety Vest",
    category: "Safety Gear",
    description: "High-visibility safety vest with reflective strips",
    imgUrl: " ../Assets/EquipmentImages/16.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "17",
    itemname: "Air Compressor",
    category: "Hard Tools",
    description: "Portable air compressor with 6-gallon tank",
    imgUrl: " ../Assets/EquipmentImages/17.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "18",
    itemname: "Forklift",
    category: "Heavy Machinery",
    description: "Toyota forklift with lifting capacity of 5000 pounds",
    imgUrl: " ../Assets/EquipmentImages/18.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "19",
    itemname: "Fall Protection Kit",
    category: "Safety Gear",
    description: "Fall protection kit with harness, lanyard, and anchor point",
    imgUrl: "../Assets/EquipmentImages/19.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "20",
    itemname: "Chainsaw",
    category: "Hard Tools",
    description: "Gas-powered chainsaw with 18-inch bar",
    imgUrl: " ../Assets/EquipmentImages/20.jpeg",
    price: 10,
    oldprice: 249,
    offer: "15",
    quantity: 1,
  },
  {
    id: "21",
    itemname: "Red Clay Bricks",
    category: "Bricks",
    description: "High-quality red clay bricks for construction",
    imgUrl: "../Assets/building/b1.jpeg",
    price: 20,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "22",
    itemname: "Concrete Bricks",
    category: "Bricks",
    description: "Concrete bricks for various construction purposes",
    imgUrl: "../Assets/building/b2.jpeg",
    price: 18,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "23",
    itemname: "Fire Bricks",
    category: "Bricks",
    description: "Fire-resistant bricks suitable for kilns and fireplaces",
    imgUrl: "../Assets/building/b3.jpeg",
    price: 25,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "24",
    itemname: "Hollow Bricks",
    category: "Bricks",
    description: "Lightweight hollow bricks for efficient construction",
    imgUrl: "../Assets/building/b4.png",
    price: 22,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "25",
    itemname: "Fly Ash Bricks",
    category: "Bricks",
    description:
      "Eco-friendly bricks made from fly ash for sustainable construction",
    imgUrl: "../Assets/building/b5.jpeg",
    price: 23,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },

  {
    id: "26",
    itemname: "Portland Cement",
    category: "Cement",
    description: "High-quality Portland cement for superior concrete strength",
    imgUrl: "../Assets/building/b6.jpeg",
    price: 50,
    oldprice: 249,

    offer: "10",
    quantity: 1,
  },
  {
    id: "27",
    itemname: "White Cement",
    category: "Cement",
    description: "Specialized white cement for architectural applications",
    imgUrl: "../Assets/building/b7.jpeg",
    price: 70,
    oldprice: 249,

    offer: "10",
    quantity: 1,
  },
  {
    id: "28",
    itemname: "Rapid Hardening Cement",
    category: "Cement",
    description: "Cement with accelerated setting time for quick construction",
    imgUrl: "../Assets/building/b8.jpeg",
    price: 60,
    oldprice: 249,

    offer: "10",
    quantity: 1,
  },
  {
    id: "29",
    itemname: "Blended Cement",
    category: "Cement",
    description:
      "Blended cement with added pozzolanic materials for enhanced durability",
    imgUrl: "../Assets/building/b9.jpeg",
    price: 55,
    oldprice: 249,

    offer: "10",
    quantity: 1,
  },
  {
    id: "30",
    itemname: "Masonry Cement",
    category: "Cement",
    description: "Specialized cement for masonry applications",
    imgUrl: "../Assets/building/b10.jpeg",
    price: 65,
    oldprice: 249,

    offer: "10",
    quantity: 1,
  },

  {
    id: "31",
    itemname: "12mm Iron Rods",
    category: "Iron",
    description:
      "High-quality 12mm iron rods for reinforcement in construction",
    imgUrl: "../Assets/building/b11.jpeg",
    price: 300,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "32",
    itemname: "10mm Iron Rods",
    category: "Iron",
    description: "Durable 10mm iron rods for structural support",
    imgUrl: "../Assets/building/b12.jpeg",
    price: 28,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "33",
    itemname: "TMT Bars",
    category: "Iron",
    description: "Thermo Mechanically Treated (TMT) bars for superior strength",
    imgUrl: "../Assets/building/b13.jpeg",
    price: 32,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "34",
    itemname: "Ribbed Bars",
    category: "Iron",
    description: "Ribbed iron bars for increased bond strength in concrete",
    imgUrl: "../Assets/building/b14.jpeg",
    price: 31,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "35",
    itemname: "Corrugated Iron Sheets",
    category: "Iron",
    description: "Corrugated iron sheets for roofing and siding applications",
    imgUrl: "../Assets/building/b15.jpeg",
    price: 35,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },

  {
    id: "36",
    itemname: "Marine Plywood",
    category: "Woods",
    description: "Marine-grade plywood for formwork and exterior applications",
    imgUrl: "../Assets/building/b16.jpeg",
    price: 150,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "37",
    itemname: "Hardwood Plywood",
    category: "Woods",
    description: "Durable hardwood plywood for various construction projects",
    imgUrl: "../Assets/building/b17.jpeg",
    price: 17,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "38",
    itemname: "Softwood Plywood",
    category: "Woods",
    description: "Lightweight softwood plywood for interior applications",
    imgUrl: "../Assets/building/b18.jpeg",
    price: 14,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "39",
    itemname: "MDF Boards",
    category: "Woods",
    description:
      "Medium Density Fiberboard (MDF) boards for furniture and cabinetry",
    imgUrl: "../Assets/building/b19.jpeg",
    price: 16,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "40",
    itemname: "Particle Boards",
    category: "Woods",
    description: "Particle boards for cost-effective construction solutions",
    imgUrl: "../Assets/building/b20.jpeg",
    price: 13,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },

  {
    id: "41",
    itemname: "Crushed Stone Aggregate",
    category: "Crushed stone",
    description:
      "Crushed stone aggregate for base material in road construction",
    imgUrl: "../Assets/building/b21.jpeg",
    price: 80,
    oldprice: 249,

    offer: "10",
    quantity: 1,
  },
  {
    id: "42",
    itemname: "Recycled Concrete Aggregate",
    category: "Crushed stone",
    description:
      "Eco-friendly recycled concrete aggregate for sustainable construction",
    imgUrl: "../Assets/building/b22.jpeg",
    price: 90,
    oldprice: 249,

    offer: "10",
    quantity: 1,
  },
  {
    id: "43",
    itemname: "Granite Chips",
    category: "Crushed stone",
    description: "Granite chips for decorative landscaping and pathways",
    imgUrl: "../Assets/building/b23.jpeg",
    price: 85,
    oldprice: 249,

    offer: "10",
    quantity: 1,
  },
  {
    id: "44",
    itemname: "Limestone Aggregate",
    category: "Crushed stone",
    description: "Limestone aggregate for drainage and erosion control",
    imgUrl: "../Assets/building/b24.jpeg",
    price: 75,
    oldprice: 249,

    offer: "10",
    quantity: 1,
  },
  {
    id: "45",
    itemname: "Quartzite Aggregate",
    category: "Crushed stone",
    description: "Quartzite aggregate for high-strength concrete mixes",
    imgUrl: "../Assets/building/b25.jpeg",
    price: 95,
    oldprice: 249,

    offer: "10",
    quantity: 1,
  },

  {
    id: "46",
    itemname: "River Sand",
    category: "Sand",
    description: "Natural river sand for concrete mixing and plastering",
    imgUrl: "../Assets/building/b26.jpeg",
    price: 12,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "47",
    itemname: "Pit Sand",
    category: "Sand",
    description: "Pit sand for various construction applications",
    imgUrl: "../Assets/building/b27.jpeg",
    price: 11,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "48",
    itemname: "Plastering Sand",
    category: "Sand",
    description: "Fine plastering sand for smooth finishes on walls",
    imgUrl: "../Assets/building/b28.jpeg",
    price: 13,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "49",
    itemname: "Filter Sand",
    category: "Sand",
    description: "Filter sand for water filtration systems and septic tanks",
    imgUrl: "../Assets/building/b29.jpeg",
    price: 12,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "50",
    itemname: "Silica Sand",
    category: "Sand",
    description: "Silica sand for glass making and industrial applications",
    imgUrl: "../Assets/building/b30.jpeg",
    price: 14,
    oldprice: 249,
    offer: "10",
    quantity: 1,
  },
  {
    id: "51",
    itemname: "Wire Cutter",
    category: "Wire Cutters",
    description: "Heavy-duty wire cutter for construction use",
    imgUrl: "../Assets/electrical/E1.jpeg",
    price: 50,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "52",
    itemname: "Steel Wire",
    category: "Wires",
    description: "High-tensile strength steel wire for construction purposes",
    imgUrl: "../Assets/electrical/e2.jpeg",
    price: 20,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "53",
    itemname: "Circuit Breaker",
    category: "Circuits",
    description: "Electrical circuit breaker for building wiring",
    imgUrl: "../Assets/electrical/e3.jpeg",
    price: 150,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "54",
    itemname: "Electrical Panel",
    category: "Panels",
    description: "Control panel for electrical distribution in buildings",
    imgUrl: "../Assets/electrical/e4.jpeg",
    price: 300,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "55",
    itemname: "Wire Stripper",
    category: "Wire Cutters",
    description: "Tool for stripping insulation from wires",
    imgUrl: "../Assets/electrical/e6.jpeg",
    price: 40,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "56",
    itemname: "Copper Wire",
    category: "Wires",
    description: "High-conductivity copper wire for electrical connections",
    imgUrl: "../Assets/electrical/e7.jpeg",
    price: 30,

    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "57",
    itemname: "Fuse Box",
    category: "Circuits",
    description: "Fuse box for electrical safety in buildings",
    imgUrl: "../Assets/electrical/e8.jpeg",
    price: 10,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "58",
    itemname: "Distribution Board",
    category: "Panels",
    description: "Distribution board for controlling electrical circuits",
    imgUrl: "../Assets/electrical/e9.jpeg",
    price: 25,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },

  {
    id: "59",
    itemname: "Wire Crimper",
    category: "Wire Cutters",
    description: "Tool for crimping wire connectors",
    imgUrl: "../Assets/electrical/e11.jpeg",
    price: 35,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "60",
    itemname: "Aluminum Wire",
    category: "Wires",
    description: "Lightweight aluminum wire for construction applications",
    imgUrl: "../Assets/electrical/e12.jpeg",
    price: 25,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "61",
    itemname: "Switch Box",
    category: "Circuits",
    description: "Switch box for controlling electrical devices",
    imgUrl: "../Assets/electrical/e13.jpeg",
    price: 80,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "62",
    itemname: "Meter Box",
    category: "Panels",
    description: "Meter box for measuring electrical consumption",
    imgUrl: "../Assets/electrical/e14.jpeg",
    price: 20,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "63",
    itemname: "Wire Bender",
    category: "Wire Cutters",
    description: "Tool for bending wires into desired shapes",
    imgUrl: "../Assets/electrical/e16.jpeg",
    price: 45,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "64",
    itemname: "Fiber Optic Cable",
    category: "Wires",
    description: "High-speed fiber optic cable for data transmission",
    imgUrl: "../Assets/electrical/e17.png",
    price: 50,

    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "65",
    itemname: "Surge Protector",
    category: "Circuits",
    description: "Surge protector for safeguarding electrical equipment",
    imgUrl: "../Assets/electrical/e18.jpeg",
    price: 12,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "66",
    itemname: "Control Panel Box",
    category: "Panels",
    description: "Control panel box for industrial automation systems",
    imgUrl: "../Assets/electrical/e19.jpeg",
    price: 40,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "67",
    itemname: "Wire Twister",
    category: "Wire Cutters",
    description: "Tool for twisting multiple wires together",
    imgUrl: "../Assets/electrical/e21.jpeg",
    price: 55,

    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "68",
    itemname: "Cat 6 Ethernet Cable",
    category: "Wires",
    description: "High-speed Ethernet cable for networking applications",
    imgUrl: "../Assets/electrical/e22.jpeg",
    price: 15,

    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "69",
    itemname: "Voltage Regulator",
    category: "Circuits",
    description: "Voltage regulator for stabilizing electrical voltage",
    imgUrl: "../Assets/electrical/e23.jpeg",
    price: 90,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "70",
    itemname: "Power Distribution Panel",
    category: "Panels",
    description: "Power distribution panel for large-scale electrical systems",
    imgUrl: "../Assets/electrical/e24.jpeg",
    price: 60,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "71",
    itemname: "PVC Pipes",
    category: "Pipes",
    description: "Durable PVC pipes for plumbing and drainage systems",
    imgUrl: "../Assets/electrical/e26.jpeg",
    price: 10,

    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "72",
    itemname: "Pipe Cutter",
    category: "Pipes",
    description: "Tool for cutting PVC and metal pipes",
    imgUrl: "../Assets/electrical/e27.jpeg",
    price: 35,

    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "73",
    itemname: "Water Pump",
    category: "Pipes",
    description: "Water pump for construction site dewatering",
    imgUrl: "../Assets/electrical/e28.jpeg",
    price: 150,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "74",
    itemname: "Pipe Fittings",
    category: "Pipes",
    description: "Various fittings for connecting PVC pipes",
    imgUrl: "../Assets/electrical/e29.jpeg",
    price: 5,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
  {
    id: "75",
    itemname: "Pipe Wrench",
    category: "Pipes",
    description: "Adjustable wrench for gripping and turning pipes",
    imgUrl: "../Assets/electrical/e30.jpeg",
    price: 20,
    oldprice: 249,
    offer: "25",
    quantity: 1,
  },
];
