export const RentalData = [
  {
    id: "1",
    category: "Tipper",
    imgUrl: "../Assets/rentalImg/tipper.webp",
    ownerName: "Prasad",
    contactNumber: "0000000000",
    amount: "1000",
  },
  {
    id: "2",
    category: "Tipper",
    imgUrl: "../Assets/rentalImg/tipper.webp",
    ownerName: "John",
    contactNumber: "1111111111",
    amount: "1100",
  },
  {
    id: "3",
    category: "Tipper",
    imgUrl: "../Assets/rentalImg/tipper.webp",
    ownerName: "Emma",
    contactNumber: "2222222222",
    amount: "1200",
  },
  {
    id: "4",
    category: "Tipper",
    imgUrl: "../Assets/rentalImg/tipper.webp",
    ownerName: "David",
    contactNumber: "3333333333",
    amount: "1300",
  },
  {
    id: "5",
    category: "Tipper",
    imgUrl: "../Assets/rentalImg/tipper.webp",
    ownerName: "Sophia",
    contactNumber: "4444444444",
    amount: "1400",
  },
  {
    id: "6",
    category: "Tipper",
    imgUrl: "../Assets/rentalImg/tipper.webp",
    ownerName: "Michael",
    contactNumber: "5555555555",
    amount: "1500",
  },
  {
    id: "7",
    category: "Tipper",
    imgUrl: "../Assets/rentalImg/tipper.webp",
    ownerName: "Linda",
    contactNumber: "6666666666",
    amount: "1600",
  },
  {
    id: "8",
    category: "Tipper",
    imgUrl: "../Assets/rentalImg/tipper.webp",
    ownerName: "James",
    contactNumber: "7777777777",
    amount: "1700",
  },
  {
    id: "9",
    category: "Tipper",
    imgUrl: "../Assets/rentalImg/tipper.webp",
    ownerName: "Olivia",
    contactNumber: "8888888888",
    amount: "1800",
  },
  {
    id: "10",
    category: "Tipper",
    imgUrl: "../Assets/rentalImg/tipper.webp",
    ownerName: "William",
    contactNumber: "9999999999",
    amount: "1900",
  },
  {
    id: "11",
    category: "Tractor",
    imgUrl: "../Assets/rentalImg/tractor.jpg",
    ownerName: "Robert",
    contactNumber: "0000000001",
    amount: "2000",
  },
  {
    id: "12",
    category: "Tractor",
    imgUrl: "../Assets/rentalImg/tractor.jpg",
    ownerName: "Emily",
    contactNumber: "1111111112",
    amount: "2100",
  },
  {
    id: "13",
    category: "Tractor",
    imgUrl: "../Assets/rentalImg/tractor.jpg",
    ownerName: "Daniel",
    contactNumber: "2222222223",
    amount: "2200",
  },
  {
    id: "14",
    category: "Tractor",
    imgUrl: "../Assets/rentalImg/tractor.jpg",
    ownerName: "Grace",
    contactNumber: "3333333334",
    amount: "2300",
  },
  {
    id: "15",
    category: "Tractor",
    imgUrl: "../Assets/rentalImg/tractor.jpg",
    ownerName: "Alexander",
    contactNumber: "4444444445",
    amount: "2400",
  },
  {
    id: "16",
    category: "Tractor",
    imgUrl: "../Assets/rentalImg/tractor.jpg",
    ownerName: "Ava",
    contactNumber: "5555555556",
    amount: "2500",
  },
  {
    id: "17",
    category: "Tractor",
    imgUrl: "../Assets/rentalImg/tractor.jpg",
    ownerName: "Samuel",
    contactNumber: "6666666667",
    amount: "2600",
  },
  {
    id: "18",
    category: "Tractor",
    imgUrl: "../Assets/rentalImg/tractor.jpg",
    ownerName: "Mia",
    contactNumber: "7777777778",
    amount: "2700",
  },
  {
    id: "19",
    category: "Tractor",
    imgUrl: "../Assets/rentalImg/tractor.jpg",
    ownerName: "Ethan",
    contactNumber: "8888888889",
    amount: "2800",
  },
  {
    id: "20",
    category: "Tractor",
    imgUrl: "../Assets/rentalImg/tractor.jpg",
    ownerName: "Charlotte",
    contactNumber: "9999999990",
    amount: "2900",
  },
  {
    id: "21",
    category: "Backhoe Loaders",
    imgUrl: "../Assets/rentalImg/loader.webp",
    ownerName: "Benjamin",
    contactNumber: "0000000002",
    amount: "3000",
  },
  {
    id: "22",
    category: "Backhoe Loaders",
    imgUrl: "../Assets/rentalImg/loader.webp",
    ownerName: "Evelyn",
    contactNumber: "1111111113",
    amount: "3100",
  },
  {
    id: "23",
    category: "Backhoe Loaders",
    imgUrl: "../Assets/rentalImg/loader.webp",
    ownerName: "Michael",
    contactNumber: "2222222224",
    amount: "3200",
  },
  {
    id: "24",
    category: "Backhoe Loaders",
    imgUrl: "../Assets/rentalImg/loader.webp",
    ownerName: "Liam",
    contactNumber: "3333333335",
    amount: "3300",
  },
  {
    id: "25",
    category: "Backhoe Loaders",
    imgUrl: "../Assets/rentalImg/loader.webp",
    ownerName: "Isabella",
    contactNumber: "4444444446",
    amount: "3400",
  },
  {
    id: "26",
    category: "Backhoe Loaders",
    imgUrl: "../Assets/rentalImg/loader.webp",
    ownerName: "Jacob",
    contactNumber: "5555555557",
    amount: "3500",
  },
  {
    id: "27",
    category: "Backhoe Loaders",
    imgUrl: "../Assets/rentalImg/loader.webp",
    ownerName: "Amelia",
    contactNumber: "6666666668",
    amount: "3600",
  },
  {
    id: "28",
    category: "Backhoe Loaders",
    imgUrl: "../Assets/rentalImg/loader.webp",
    ownerName: "Mason",
    contactNumber: "7777777779",
    amount: "3700",
  },
  {
    id: "29",
    category: "Backhoe Loaders",
    imgUrl: "../Assets/rentalImg/loader.webp",
    ownerName: "Harper",
    contactNumber: "8888888880",
    amount: "3800",
  },
  {
    id: "30",
    category: "Backhoe Loaders",
    imgUrl: "../Assets/rentalImg/loader.webp",
    ownerName: "William",
    contactNumber: "9999999991",
    amount: "3900",
  },
  {
    id: "31",
    category: "Dump Trucks",
    imgUrl: "../Assets/rentalImg/truck.jpg",
    ownerName: "Liam",
    contactNumber: "0000000003",
    amount: "4000",
  },
  {
    id: "32",
    category: "Dump Trucks",
    imgUrl: "../Assets/rentalImg/truck.jpg",
    ownerName: "Charlotte",
    contactNumber: "1111111114",
    amount: "4100",
  },
  {
    id: "33",
    category: "Dump Trucks",
    imgUrl: "../Assets/rentalImg/truck.jpg",
    ownerName: "Mason",
    contactNumber: "2222222225",
    amount: "4200",
  },
  {
    id: "34",
    category: "Dump Trucks",
    imgUrl: "../Assets/rentalImg/truck.jpg",
    ownerName: "Amelia",
    contactNumber: "3333333336",
    amount: "4300",
  },
  {
    id: "35",
    category: "Dump Trucks",
    imgUrl: "../Assets/rentalImg/truck.jpg",
    ownerName: "Jacob",
    contactNumber: "4444444447",
    amount: "4400",
  },
  {
    id: "36",
    category: "Dump Trucks",
    imgUrl: "../Assets/rentalImg/truck.jpg",
    ownerName: "William",
    contactNumber: "5555555558",
    amount: "4500",
  },
  {
    id: "37",
    category: "Dump Trucks",
    imgUrl: "../Assets/rentalImg/truck.jpg",
    ownerName: "Harper",
    contactNumber: "6666666669",
    amount: "4600",
  },
  {
    id: "38",
    category: "Dump Trucks",
    imgUrl: "../Assets/rentalImg/truck.jpg",
    ownerName: "James",
    contactNumber: "7777777780",
    amount: "4700",
  },
  {
    id: "39",
    category: "Dump Trucks",
    imgUrl: "../Assets/rentalImg/truck.jpg",
    ownerName: "Evelyn",
    contactNumber: "8888888881",
    amount: "4800",
  },
  {
    id: "40",
    category: "Dump Trucks",
    imgUrl: "../Assets/rentalImg/truck.jpg",
    ownerName: "Oliver",
    contactNumber: "9999999992",
    amount: "4900",
  },
  {
    id: "41",
    category: "Cranes",
    imgUrl: "../Assets/rentalImg/crane.webp",
    ownerName: "Elijah",
    contactNumber: "0000000004",
    amount: "5000",
  },
  {
    id: "42",
    category: "Cranes",
    imgUrl: "../Assets/rentalImg/crane.webp",
    ownerName: "Olivia",
    contactNumber: "1111111115",
    amount: "5100",
  },
  {
    id: "43",
    category: "Cranes",
    imgUrl: "../Assets/rentalImg/crane.webp",
    ownerName: "Ethan",
    contactNumber: "2222222226",
    amount: "5200",
  },
  {
    id: "44",
    category: "Cranes",
    imgUrl: "../Assets/rentalImg/crane.webp",
    ownerName: "Amelia",
    contactNumber: "3333333337",
    amount: "5300",
  },
  {
    id: "45",
    category: "Cranes",
    imgUrl: "../Assets/rentalImg/crane.webp",
    ownerName: "Mia",
    contactNumber: "4444444448",
    amount: "5400",
  },
  {
    id: "46",
    category: "Cranes",
    imgUrl: "../Assets/rentalImg/crane.webp",
    ownerName: "James",
    contactNumber: "5555555559",
    amount: "5500",
  },
  {
    id: "47",
    category: "Cranes",
    imgUrl: "../Assets/rentalImg/crane.webp",
    ownerName: "Lucas",
    contactNumber: "6666666670",
    amount: "5600",
  },
  {
    id: "48",
    category: "Cranes",
    imgUrl: "../Assets/rentalImg/crane.webp",
    ownerName: "Ava",
    contactNumber: "7777777781",
    amount: "5700",
  },
  {
    id: "49",
    category: "Cranes",
    imgUrl: "../Assets/rentalImg/crane.webp",
    ownerName: "Oliver",
    contactNumber: "8888888882",
    amount: "5800",
  },
  {
    id: "50",
    category: "Cranes",
    imgUrl: "../Assets/rentalImg/crane.webp",
    ownerName: "Charlotte",
    contactNumber: "9999999993",
    amount: "5900",
  },
  {
    id: "51",
    category: "Motor Graders",
    imgUrl: "../Assets/rentalImg/Motor Graders.webp",
    ownerName: "Prasad",
    contactNumber: "0000000000",
    amount: "1000",
  },
  {
    id: "52",
    category: "Motor Graders",
    imgUrl: "../Assets/rentalImg/Motor Graders.webp",
    ownerName: "John",
    contactNumber: "1111111111",
    amount: "1100",
  },
  {
    id: "53",
    category: "Motor Graders",
    imgUrl: "../Assets/rentalImg/Motor Graders.webp",
    ownerName: "Emma",
    contactNumber: "2222222222",
    amount: "1200",
  },
  {
    id: "54",
    category: "Motor Graders",
    imgUrl: "../Assets/rentalImg/Motor Graders.webp",
    ownerName: "David",
    contactNumber: "3333333333",
    amount: "1300",
  },
  {
    id: "55",
    category: "Motor Graders",
    imgUrl: "../Assets/rentalImg/Motor Graders.webp",
    ownerName: "Sophia",
    contactNumber: "4444444444",
    amount: "1400",
  },
  {
    id: "56",
    category: "Motor Graders",
    imgUrl: "../Assets/rentalImg/Motor Graders.webp",
    ownerName: "Michael",
    contactNumber: "5555555555",
    amount: "1500",
  },
  {
    id: "57",
    category: "Motor Graders",
    imgUrl: "../Assets/rentalImg/Motor Graders.webp",
    ownerName: "Linda",
    contactNumber: "6666666666",
    amount: "1600",
  },
  {
    id: "58",
    category: "Motor Graders",
    imgUrl: "../Assets/rentalImg/Motor Graders.webp",
    ownerName: "James",
    contactNumber: "7777777777",
    amount: "1700",
  },

  {
    id: "59",
    category: "Motor Graders",
    imgUrl: "../Assets/rentalImg/Motor Graders.webp",
    ownerName: "Olivia",
    contactNumber: "8888888888",
    amount: "1800",
  },
  {
    id: "60",
    category: "Motor Graders",
    imgUrl: "../Assets/rentalImg/Motor Graders.webp",
    ownerName: "William",
    contactNumber: "9999999999",
    amount: "1900",
  },
  {
    id: "61",
    category: "Concrete Mixers",
    imgUrl: "../Assets/rentalImg/Concretemixer.jpeg",
    ownerName: "Robert",
    contactNumber: "0000000001",
    amount: "2000",
  },
  {
    id: "62",
    category: "Concrete Mixers",
    imgUrl: "../Assets/rentalImg/Concretemixer.jpeg",
    ownerName: "Emily",
    contactNumber: "1111111112",
    amount: "2100",
  },
  {
    id: "63",
    category: "Concrete Mixers",
    imgUrl: "../Assets/rentalImg/Concretemixer.jpeg",
    ownerName: "Daniel",
    contactNumber: "2222222223",
    amount: "2200",
  },
  {
    id: "64",
    category: "Concrete Mixers",
    imgUrl: "../Assets/rentalImg/Concretemixer.jpeg",
    ownerName: "Grace",
    contactNumber: "3333333334",
    amount: "2300",
  },
  {
    id: "65",
    category: "Concrete Mixers",
    imgUrl: "../Assets/rentalImg/Concretemixer.jpeg",
    ownerName: "Alexander",
    contactNumber: "4444444445",
    amount: "2400",
  },
  {
    id: "66",
    category: "Concrete Mixers",
    imgUrl: "../Assets/rentalImg/Concretemixer.jpeg",
    ownerName: "Ava",
    contactNumber: "5555555556",
    amount: "2500",
  },
  {
    id: "67",
    category: "Concrete Mixers",
    imgUrl: "../Assets/rentalImg/Concretemixer.jpeg",
    ownerName: "Samuel",
    contactNumber: "6666666667",
    amount: "2600",
  },
  {
    id: "68",
    category: "Concrete Mixers",
    imgUrl: "../Assets/rentalImg/Concretemixer.jpeg",
    ownerName: "Mia",
    contactNumber: "7777777778",
    amount: "2700",
  },
  {
    id: "69",
    category: "Concrete Mixers",
    imgUrl: "../Assets/rentalImg/Concretemixer.jpeg",
    ownerName: "Ethan",
    contactNumber: "8888888889",
    amount: "2800",
  },
  {
    id: "70",
    category: "Concrete Mixers",
    imgUrl: "../Assets/rentalImg/Concretemixer.jpeg",
    ownerName: "Charlotte",
    contactNumber: "9999999990",
    amount: "2900",
  },
  {
    id: "71",
    category: "Excavators",
    imgUrl: "../Assets/rentalImg/excavator.jpg",
    ownerName: "Benjamin",
    contactNumber: "0000000007",
    amount: "3000",
  },
  {
    id: "72",
    category: "Excavators",
    imgUrl: "../Assets/rentalImg/excavator.jpg",
    ownerName: "Evelyn",
    contactNumber: "1111111113",
    amount: "3100",
  },
  {
    id: "73",
    category: "Excavators",
    imgUrl: "../Assets/rentalImg/excavator.jpg",
    ownerName: "Michael",
    contactNumber: "2222222224",
    amount: "3200",
  },
  {
    id: "74",
    category: "Excavators",
    imgUrl: "../Assets/rentalImg/excavator.jpg",
    ownerName: "Liam",
    contactNumber: "3333333335",
    amount: "3300",
  },
  {
    id: "75",
    category: "Excavators",
    imgUrl: "../Assets/rentalImg/excavator.jpg",
    ownerName: "Isabella",
    contactNumber: "4444444446",
    amount: "3400",
  },
  {
    id: "76",
    category: "Excavators",
    imgUrl: "../Assets/rentalImg/excavator.jpg",
    ownerName: "Jacob",
    contactNumber: "5555555557",
    amount: "3500",
  },
  {
    id: "77",
    category: "Excavators",
    imgUrl: "../Assets/rentalImg/excavator.jpg",
    ownerName: "Amelia",
    contactNumber: "6666666668",
    amount: "3600",
  },
  {
    id: "78",
    category: "Excavators",
    imgUrl: "../Assets/rentalImg/excavator.jpg",
    ownerName: "Mason",
    contactNumber: "7777777779",
    amount: "3700",
  },
  {
    id: "79",
    category: "Excavators",
    imgUrl: "../Assets/rentalImg/excavator.jpg",
    ownerName: "Harper",
    contactNumber: "8888888880",
    amount: "3800",
  },
  {
    id: "80",
    category: "Excavators",
    imgUrl: "../Assets/rentalImg/excavator.jpg",
    ownerName: "William",
    contactNumber: "9999999991",
    amount: "3900",
  },
  {
    id: "81",
    category: "Bulldozers",
    imgUrl: "../Assets/rentalImg/dozer.jpeg",
    ownerName: "Liam",
    contactNumber: "0000000003",
    amount: "4000",
  },
  {
    id: "82",
    category: "Bulldozers",
    imgUrl: "../Assets/rentalImg/dozer.jpeg",
    ownerName: "Charlotte",
    contactNumber: "1111111114",
    amount: "4100",
  },
  {
    id: "83",
    category: "Bulldozers",
    imgUrl: "../Assets/rentalImg/dozer.jpeg",
    ownerName: "Mason",
    contactNumber: "2222222225",
    amount: "4200",
  },
  {
    id: "84",
    category: "Bulldozers",
    imgUrl: "../Assets/rentalImg/dozer.jpeg",
    ownerName: "Amelia",
    contactNumber: "3333333336",
    amount: "4300",
  },
  {
    id: "85",
    category: "Bulldozers",
    imgUrl: "../Assets/rentalImg/dozer.jpeg",
    ownerName: "Jacob",
    contactNumber: "4444444447",
    amount: "4400",
  },
  {
    id: "86",
    category: "Bulldozers",
    imgUrl: "../Assets/rentalImg/dozer.jpeg",
    ownerName: "William",
    contactNumber: "5555555558",
    amount: "4500",
  },
  {
    id: "87",
    category: "Bulldozers",
    imgUrl: "../Assets/rentalImg/dozer.jpeg",
    ownerName: "Harper",
    contactNumber: "6666666669",
    amount: "4600",
  },
  {
    id: "88",
    category: "Bulldozers",
    imgUrl: "../Assets/rentalImg/dozer.jpeg",
    ownerName: "James",
    contactNumber: "7777777780",
    amount: "4700",
  },
  {
    id: "89",
    category: "Bulldozers",
    imgUrl: "../Assets/rentalImg/dozer.jpeg",
    ownerName: "Evelyn",
    contactNumber: "8888888881",
    amount: "4800",
  },
  {
    id: "90",
    category: "Bulldozers",
    imgUrl: "../Assets/rentalImg/dozer.jpeg",
    ownerName: "Oliver",
    contactNumber: "9999999992",
    amount: "4900",
  },
  {
    id: "91",
    category: "Scrapers",
    imgUrl: "../Assets/rentalImg/Scrap.jpeg",
    ownerName: "Elijah",
    contactNumber: "0000000004",
    amount: "5000",
  },
  {
    id: "92",
    category: "Scrapers",
    imgUrl: "../Assets/rentalImg/Scrap.jpeg",
    ownerName: "Olivia",
    contactNumber: "1111111115",
    amount: "5100",
  },
  {
    id: "93",
    category: "Scrapers",
    imgUrl: "../Assets/rentalImg/Scrap.jpeg",
    ownerName: "Ethan",
    contactNumber: "2222222226",
    amount: "5200",
  },
  {
    id: "94",
    category: "Scrapers",
    imgUrl: "../Assets/rentalImg/Scrap.jpeg",
    ownerName: "Amelia",
    contactNumber: "3333333337",
    amount: "5300",
  },
  {
    id: "95",
    category: "Scrapers",
    imgUrl: "../Assets/rentalImg/Scrap.jpeg",
    ownerName: "Mia",
    contactNumber: "4444444448",
    amount: "5400",
  },
  {
    id: "96",
    category: "Scrapers",
    imgUrl: "../Assets/rentalImg/Scrap.jpeg",
    ownerName: "James",
    contactNumber: "5555555559",
    amount: "5500",
  },
  {
    id: "97",
    category: "Scrapers",
    imgUrl: "../Assets/rentalImg/Scrap.jpeg",
    ownerName: "Lucas",
    contactNumber: "6666666670",
    amount: "5600",
  },
  {
    id: "98",
    category: "Scrapers",
    imgUrl: "../Assets/rentalImg/Scrap.jpeg",
    ownerName: "Ava",
    contactNumber: "7777777781",
    amount: "5700",
  },
  {
    id: "99",
    category: "Scrapers",
    imgUrl: "../Assets/rentalImg/Scrap.jpeg",
    ownerName: "Oliver",
    contactNumber: "8888888882",
    amount: "5800",
  },
  {
    id: "100",
    category: "Scrapers",
    imgUrl: "../Assets/rentalImg/Scrap.jpeg",
    ownerName: "Charlotte",
    contactNumber: "9999999993",
    amount: "5900",
  },
];
