export const vehicles = [
  { id: 1, name: "Tipper", imgUrl: "../Assets/rentalImg/icons/tipper.png" },
  { id: 2, name: "Tractor", imgUrl: "../Assets/rentalImg/icons/tractor.png" },
  { id: 3, name: "loader", imgUrl: "../Assets/rentalImg/icons/loader.png" },
  { id: 4, name: "Truck", imgUrl: "../Assets/rentalImg/icons/truck.png" },
  { id: 5, name: "Crane", imgUrl: "../Assets/rentalImg/icons/crane.png" },
  {
    id: 6,
    name: "Excavator",
    imgUrl: "../Assets/rentalImg/icons/excavator.png",
  },
  { id: 7, name: "Dozer", imgUrl: "../Assets/rentalImg/icons/dozer.png" },
  { id: 8, name: "Scrap", imgUrl: "../Assets/rentalImg/icons/Scrap.png" },
  {
    id: 9,
    name: "Concrete mixer",
    imgUrl: "../Assets/rentalImg/icons/Concretemixer.png",
  },
  {
    id: 10,
    name: "Crusher plant",
    imgUrl: "../Assets/rentalImg/icons/Crusherplant.png",
  },
];
export const sellers = [
  {
    id: "1",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Nalgonda,Telangana",
    model: "Tractor Model 1",
    price: 45000,
    description: "Versatile tractor suitable for various agricultural tasks.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567890",
  },
  {
    id: "2",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "LB Nagar, Hyderabad, Telangana",
    model: "Tractor Model 2",
    price: 48000,
    description:
      "Powerful tractor with advanced features for efficient farming.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567891",
  },
  {
    id: "3",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Kattangur,Nalgonda,Telangana",
    model: "Tractor Model 3",
    price: 42000,
    description:
      "Compact tractor suitable for small-scale farming and gardening.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567892",
  },
  {
    id: "4",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Mallaram,Nalgonda,Telangana",
    model: "Tractor Model 4",
    price: 50000,
    description: "Heavy-duty tractor for large-scale agricultural operations.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567893",
  },
  {
    id: "5",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Nalgonda,Telangana",
    model: "Tractor Model 5",
    price: 46000,
    description:
      "Efficient tractor with a high horsepower engine for demanding tasks.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567894",
  },
  {
    id: "6",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Gudem,Nalgonda,Telangana",
    model: "Tractor Model 6",
    price: 49000,
    description:
      "Reliable tractor equipped with modern technology for precision farming.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567895",
  },
  {
    id: "7",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Gattu,Nalgonda,Telangana",
    model: "Tractor Model 7",
    price: 47000,
    description:
      "Sturdy tractor designed to handle tough terrain and heavy loads.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567896",
  },
  {
    id: "8",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Cheruvu,Nalgonda,Telangana",
    model: "Tractor Model 8",
    price: 51000,
    description:
      "Versatile tractor suitable for both agricultural and industrial use.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567897",
  },
  {
    id: "9",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "Vaguneru,Nalgonda,Telangana",
    model: "Tractor Model 9",
    price: 48000,
    description:
      "Compact tractor with excellent maneuverability for tight spaces.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567898",
  },
  {
    id: "10",
    vehicle: "Tractor",
    owner: "Virat",
    Location: "MarrigudaNalgonda,Telangana",
    model: "Tractor Model 10",
    price: 52000,
    description:
      "Heavy-duty tractor with a comfortable cabin for long hours of operation.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567899",
  },
  {
    id: "11",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 1",
    price: 60000,
    Location: "Nalgonda",
    description:
      "Heavy-duty tipper truck suitable for bulk material transportation.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567890",
  },
  {
    id: "12",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 2",
    price: 55000,
    Location: "Nalgonda",
    description:
      "Durable tipper truck with a large capacity for industrial use.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567891",
  },
  {
    id: "13",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 3",
    price: 58000,
    Location: "Nalgonda",
    description:
      "Efficient tipper truck for construction and material hauling.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567892",
  },
  {
    id: "14",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 4",
    Location: "Nalgonda",
    price: 62000,
    description: "Reliable tipper truck for heavy-duty transportation tasks.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567893",
  },
  {
    id: "15",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 5",
    price: 57000,
    Location: "Nalgonda",
    description:
      "Robust tipper truck designed for tough construction environments.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567894",
  },
  {
    id: "16",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 6",
    price: 63000,
    Location: "Nalgonda",
    description:
      "High-capacity tipper truck for large-scale material transport.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567895",
  },
  {
    id: "17",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 7",
    price: 59000,
    Location: "Nalgonda",
    description:
      "Versatile tipper truck suitable for various construction projects.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567896",
  },
  {
    id: "18",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 8",
    price: 65000,
    Location: "Nalgonda",
    description:
      "Heavy-duty tipper truck with advanced features for efficient operation.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567897",
  },
  {
    id: "19",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 9",
    price: 60000,
    Location: "Nalgonda",
    description:
      "Reliable tipper truck for construction and industrial applications.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567898",
  },
  {
    id: "20",
    vehicle: "Tipper",
    owner: "Peter",
    model: "Tipper Model 10",
    price: 62000,
    Location: "Nalgonda",
    description:
      "Sturdy tipper truck designed to withstand heavy loads and rough terrain.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567899",
  },
  {
    id: "21",
    vehicle: "loader",
    owner: "Peter",
    model: "Loader Model 1",
    price: 75000,
    Location: "Nalgonda",
    description:
      "Heavy-duty loader for construction and material handling tasks.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567800",
  },
  {
    id: "22",
    vehicle: "loader",
    owner: "Peter",
    model: "Loader Model 2",
    Location: "Nalgonda",
    price: 80000,
    description:
      "Versatile loader with a large bucket capacity for various applications.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567801",
  },
  {
    id: "221",
    vehicle: "Truck",
    owner: "John",
    model: "Truck Model A",
    price: 85000,
    Location: "Hyderabad",
    description:
      "Heavy-duty truck suitable for long-distance transport and heavy loads.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567810",
  },
  {
    id: "23",
    vehicle: "Crane",
    owner: "Michael",
    model: "Crane Model B",
    price: 95000,
    Location: "Warangal",
    description:
      "High-capacity crane for construction and heavy lifting tasks.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567820",
  },
  {
    id: "24",
    vehicle: "Excavator",
    owner: "Alice",
    model: "Excavator Model C",
    price: 105000,
    Location: "Vijayawada",
    description: "Powerful excavator ideal for digging and earth-moving tasks.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567830",
  },
  {
    id: "25",
    vehicle: "Dozer",
    owner: "Emma",
    model: "Dozer Model D",
    price: 95000,
    Location: "Khammam",
    description: "Heavy-duty dozer for land clearing and grading tasks.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567840",
  },
  {
    id: "26",
    vehicle: "Scrap",
    owner: "Olivia",
    model: "Scrap Handler Model E",
    price: 65000,
    Location: "Karimnagar",
    description: "Efficient scrap handler for recycling and material handling.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567850",
  },
  {
    id: "27",
    vehicle: "Concrete mixer",
    owner: "Liam",
    model: "Concrete Mixer Model F",
    price: 55000,
    Location: "Mahbubnagar",
    description: "Reliable concrete mixer for construction and paving tasks.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567860",
  },
  {
    id: "28",
    vehicle: "Crusher plant",
    owner: "Noah",
    model: "Crusher Plant Model G",
    price: 125000,
    Location: "Rangareddy",
    description:
      "High-efficiency crusher plant for stone and aggregate processing.",
    imagesList: [
      "../Assets/rentalImg/sell/t1.jpg",
      "../Assets/rentalImg/sell/t2.jpg",
      "../Assets/rentalImg/sell/t3.jpg",
      "../Assets/rentalImg/sell/t4.jpg",
    ],
    contactNumber: "+1234567870",
  },
];
